version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking AWS CLI version...."
      - aws --version
      - rm -rf node_modules
      - rm -f package-lock.json
      - echo "Installing NPM dependencies..."
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E3RJXHUX4CJ3LK --paths "/*"
      
artifacts:
  files:
    - '**/*'
  base-directory: build
