version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking AWS CLI version..."
      - aws --version
      - echo "Cleaning up old dependencies..."
      - rm -rf node_modules package-lock.json
      - echo "Installing optimized dependencies..."
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Build started on `date`"
      - export NODE_OPTIONS="--max-old-space-size=2048"
      - echo "Building the project with optimized memory for 3GB environment..."
      - npm run build --max-workers=2

  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E3RJXHUX4CJ3LK --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - node_modules
