// Define all the route paths as constants
export const ROUTES = {
  HOME_SCREEN: "/homescreen",
  SIGN_UP: "/signup",
  SIGN_IN: "/signin",
  JOBS: "/jobs",
  APPLYJOB: "/applyjob",
  CREATE_JOB: "/createjob",
  FORGET_PASSWORD: "/forgetpassword",
  VERIFY_SCREEN: "/verifyscreen",
  NOTIFICATION_ALLOW: "/notificationallow",
  PREFERRED_ROLE: "/xpertrole",
  USER_TYPE: "/usertype",
  INTERN: "/intern",
  TEAMS: "/teams",
  LANDING_PAGE: "/",
  NOTIFICATION: "/notification",
  SINGLE_COURSE_DESCRIPTION: "/service/:projectId",

  APPLY_COUPON: "/apply-coupon",
  FILTER_SCREEN: "/filter-screen",
  BOOKMARK: "/bookmark",
  CHAT_SCREEN: "/chat-screen",
  SINGLE_CHAT_SCREEN: "/single-chat-screen",
  PROFILE: "/profile/:uid",
  ENTREPRENEUR: "/entrepreneur/:uid",
  PROFILE_EDIT: "/profile-edit",
  WALLET_SCREEN: "/wallet-screen",
  WALLET: "/wallet",
  NOTIFICATION_OPTION: "/notification-option",
  ABOUT_US_SCREEN: "/about-us-screen",
  POLICY_SCREEN: "/policy-screen",
  FAQ_SCREEN: "/faq-screen",
  FEEDBACK_SCREEN: "/feedback-screen",
  REVIEW_SCREEN: "/review-screen",
  INTERNSHIP: "/internship",
  APPLY_INTERNSHIP: "/applyinternship",
  USER_PROFILE: "/userprofile",
  FILTER_SCREEN: "/filterscreen/:type",
  // PROFESSIONAL_PROFILE: "/professionalProfile/:profession",
  CARD_DESIGN: "/cardDesign",
  STEPPER_FORM: "/userdetail",
  ENTREPRENEURS_FORM: "/entrepreneurdetails",
  //chats
  CHAT: "/chat",
  MYCHAT: "/mychat",
  //video call
  VIDEOCALL: "/videocall",
  MYVIDEOCALL: "/myvideocall",
  JOBSPOSTINGS: "/jobpostings/",
  JOBSTATS: "/jobstats/:jobId",
  VIEWJOB: "/viewjob/:jobId",
  CHOOSETYPE: "/choosetype",
  EDITJOB: "/editjob/:jobId",
  SUPER_USER: "/superuser"
};
